name: push container to registry
outputs:
  digest:
    value: ${{ steps.push.outputs.digest }}

runs:
  using: composite
  steps:
    - name: Install Cosign
      if: ${{ env.signing_key }}
      uses: sigstore/cosign-installer@v4.1.1

    - name: Login to registry
      shell: bash
      run: |
        sudo podman login --username $username --password $password $registry
        echo "$password" | docker login -u $username --password-stdin $registry # for cosign

    - name: Push to registry
      id: push
      shell: bash
      run: |
        # HACK: push twice as a workaround to push rechunk annotations
        sudo podman push --digestfile=/tmp/digestfile $registry/$name:$tag
        echo "digest=$(< /tmp/digestfile)" | tee "${GITHUB_OUTPUT}"
        sudo podman push --digestfile=/tmp/digestfile $registry/$name:$tag
        echo "digest=$(< /tmp/digestfile)" | tee "${GITHUB_OUTPUT}"

    - name: Sign with cosign
      if: ${{ env.signing_key }}
      shell: bash
      run: |
        cosign sign -y --new-bundle-format=false --use-signing-config=false --key env://signing_key "$registry/$name@${{ steps.push.outputs.digest }}"

    - name: Latest
      if: ${{ env.latest }}
      shell: bash
      run: |
        sudo podman image tag $registry/$name:$tag $registry/$name:latest
        sudo podman push $registry/$name:latest
        sudo podman push $registry/$name:latest
