name: push container to registry
outputs:
  digest:
    value: ${{ steps.push.outputs.digest }}

runs:
  using: composite
  steps:
    - name: Install Cosign
      if: ${{ env.signing_key }}
      uses: sigstore/cosign-installer@v4.1.1

    - name: Login to registry
      shell: bash
      run: |
        sudo podman login --username $username --password $password $registry
        echo "$password" | docker login -u $username --password-stdin $registry # for cosign

    - name: Push to registry
      id: push
      shell: bash
      run: |
        # retry 3 times
        function push {
          n=0
          until [ "$n" -ge 3 ]; do
            sudo podman push --digestfile=/tmp/digestfile $registry/$name:$tag && break
            n=$((n+1))
            sleep 10
          done

          if [ "$n" -ge 3 ]; then
             exit 1
          fi
        }

        # HACK: push twice as a workaround to push rechunk annotations
        push
        push

        echo "digest=$(< /tmp/digestfile)" | tee "${GITHUB_OUTPUT}"

    - name: Sign with cosign
      if: ${{ env.signing_key }}
      shell: bash
      run: |
        cosign sign -y --new-bundle-format=false --use-signing-config=false --key env://signing_key "$registry/$name@${{ steps.push.outputs.digest }}"

    - name: Latest
      if: ${{ env.latest }}
      shell: bash
      run: |
        sudo podman image tag $registry/$name:$tag $registry/$name:latest

        function push {
          n=0
          until [ "$n" -ge 3 ]; do
            sudo podman push $registry/$name:latest && break
            n=$((n+1))
            sleep 10
          done

          if [ "$n" -ge 3 ]; then
             exit 1
          fi
        }

        push
        push
