name: push container to registry
runs:
  using: composite
  steps:
    - name: Login to registry
      shell: bash
      run: |
        sudo podman login --username $username --password $password $registry
    - name: Push to registry
      shell: bash
      run: |
        sudo podman push $registry/$name:$tag
    - name: Latest
      if: ${{ env.latest }}
      shell: bash
      run: |
        sudo podman image tag $registry/$name:$tag $registry/$name:latest
        sudo podman push $registry/$name:latest
