name: "Create partition images"
inputs:
  config_file:
    required: true
    type: string
  rootfs:
    type: string
    default: btrfs
  install_dtb:
    type: boolean
    default: false
  registry:
    required: true
    type: string
  image_name:
    required: true
    type: string
  image_tag:
    type: string
    default: '42'

runs:
  using: "composite"
  steps:
    - name: Build disk image
      id: build-raw
      uses: osbuild/bootc-image-builder-action@v0.0.2
      with:
        config-file: ${{ inputs.config_file }}
        image: ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
        rootfs: ${{ inputs.rootfs }}
        types: |
          raw

    - name: Post-process images
      env:
        FULL_IMAGE: ${{ steps.build-raw.outputs.output-directory }}
        INSTALL_DTB: ${{ inputs.install_dtb }}
      run: ${{ github.action_path }}/postprocess.sh
      shell: bash
