name: images
inputs:
  device:
    required: true
    type: string
  registry:
    required: true
    type: string
  image_name:
    required: true
    type: string
  image_tag:
    required: true
    type: string
  args_7z:
    type: string
    default: ''
  rootfs:
    type: string
    default: btrfs
  build_aux:
    type: string
    description: name of the build-aux directory
    default: 'build-aux'

runs:
  using: composite
  steps:
    - name: Install latest 7z
      shell: bash
      run: |
        curl -L https://7-zip.org/a/7z2501-linux-arm64.tar.xz | tar -xJf -
        sudo cp 7zzs /bin/7z
    - name: Get device config
      id: conf
      shell: bash
      run: |
        cat 'devices/${{ inputs.device }}/${{ inputs.build_aux }}/device.conf' >> $GITHUB_OUTPUT
    - name: Install erofs-utils
      if: ${{ steps.conf.outputs.build_erofs == 'true' }}
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y erofs-utils
    - name: Build disk image
      id: build-raw
      uses: osbuild/bootc-image-builder-action@v0.0.2
      with:
        config-file: ${{ github.workspace }}/bootc-image-builder.toml
        image: ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
        rootfs: ${{ inputs.rootfs }}
        types: |
          raw
    - name: Post-process images
      env:
        CONF_ESP_SIZE: ${{ steps.conf.outputs.esp_size }}
        CONF_ESP_SECTOR_SIZE: ${{ steps.conf.outputs.esp_sector_size || '4096' }}
        CONF_BOOT_SIZE: ${{ steps.conf.outputs.boot_size }}
        CONF_INSTALL_DTB: ${{ steps.conf.outputs.install_dtb }}
        CONF_SPLIT_PARTITIONS: ${{ steps.conf.outputs.split_partitions }}
        CONF_BUILD_EROFS: ${{ steps.conf.outputs.build_erofs || 'false' }}
        ROOTFS_TYPE: ${{ inputs.rootfs }}
        FULL_IMAGE: ${{ steps.build-raw.outputs.output-directory }}
        ACTION_PATH: ${{ github.action_path }}
        BUILD_AUX: ${{ inputs.build_aux }}
        OCI_IMAGE: ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
      shell: bash
      run: ${{ github.action_path }}/postprocess.sh

    - name: Collect artifacts
      shell: bash
      env:
        DEVICE_PATH: devices/${{ inputs.device }}
        IMAGE_NAME: ${{ inputs.image_name }}
        IMAGE_TAG: ${{ inputs.image_tag }}
        ARGS_7Z: ${{ inputs.args_7z}}
        ACTION_PATH: ${{ github.action_path }}
        BUILD_AUX: ${{ inputs.build_aux }}
      run: ${{ github.action_path }}/collect-artifacts.sh
